# .github/workflows/selftest.yaml
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: Apache-2.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  selftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v3
      - uses: ./
      - name: Run Incus commands
        run: |
          set -x
          incus admin init --auto
          incus launch images:debian/12/cloud c1
          incus exec c1 -- cloud-init status --wait
          incus exec c1 -- cat /etc/os-release
      - run: yamllint .
      - run: npm exec --yes embedme -- --verify README.md
# vim: set filetype=yaml.action :
